/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AdmissionStatus = IDL.Variant({
  'pending' : IDL.Null,
  'admitted' : IDL.Null,
  'rejected' : IDL.Null,
});
export const FeeType = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'session' : IDL.Text,
  'amount' : IDL.Nat,
  'programme' : IDL.Text,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const Result = IDL.Record({
  'studentId' : IDL.Text,
  'semester' : IDL.Text,
  'score' : IDL.Nat,
  'grade' : IDL.Text,
  'courseId' : IDL.Nat,
});
export const PaymentRecord = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Variant({ 'pending' : IDL.Null, 'completed' : IDL.Null }),
  'paymentMethod' : IDL.Text,
  'studentId' : IDL.Text,
  'date' : IDL.Int,
  'feeType' : IDL.Text,
  'reference' : IDL.Text,
  'amount' : IDL.Nat,
});
export const AdmissionApplication = IDL.Record({
  'id' : IDL.Nat,
  'status' : AdmissionStatus,
  'documents' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'programmeChoice' : IDL.Text,
  'jambNumber' : IDL.Text,
  'oLevelResults' : IDL.Vec(IDL.Text),
});
export const HostelApplication = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  }),
  'studentId' : IDL.Text,
  'session' : IDL.Text,
  'roomType' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'staff' : IDL.Null,
  'student' : IDL.Null,
  'parent' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'principal' : IDL.Principal,
  'name' : IDL.Text,
  'role' : UserRole,
  'email' : IDL.Text,
  'idNumber' : IDL.Text,
});
export const Announcement = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'timestamp' : IDL.Int,
  'targetRole' : IDL.Text,
});
export const Course = IDL.Record({
  'id' : IDL.Nat,
  'semester' : IDL.Text,
  'code' : IDL.Text,
  'name' : IDL.Text,
  'programme' : IDL.Text,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCourse' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  'addFeeType' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text, IDL.Text], [], []),
  'addResult' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Nat],
      [],
      [],
    ),
  'addStudentProfile' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'applyForHostel' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'assignAccessRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'checkAdmissionStatus' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(AdmissionStatus)],
      ['query'],
    ),
  'checkAdmissionStatusByName' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(AdmissionStatus)],
      ['query'],
    ),
  'checkUnpaidFees' : IDL.Func([], [IDL.Vec(FeeType)], ['query']),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'deregisterCourse' : IDL.Func([IDL.Nat], [], []),
  'getAggregatedStudentData' : IDL.Func(
      [],
      [IDL.Vec(Result), IDL.Vec(PaymentRecord)],
      [],
    ),
  'getAllAdmissionApplications' : IDL.Func(
      [],
      [IDL.Vec(AdmissionApplication)],
      ['query'],
    ),
  'getAllHostelApplications' : IDL.Func(
      [],
      [IDL.Vec(HostelApplication)],
      ['query'],
    ),
  'getAllPayments' : IDL.Func([], [IDL.Vec(PaymentRecord)], ['query']),
  'getAllResults' : IDL.Func([], [IDL.Vec(Result)], ['query']),
  'getAllStudents' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getAllUserProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getAnnouncements' : IDL.Func([IDL.Text], [IDL.Vec(Announcement)], ['query']),
  'getCallerRole' : IDL.Func([], [IDL.Opt(UserRole)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
  'getFeeTypes' : IDL.Func([], [IDL.Vec(FeeType)], ['query']),
  'getMyHostelApplication' : IDL.Func(
      [],
      [IDL.Opt(HostelApplication)],
      ['query'],
    ),
  'getPaymentHistory' : IDL.Func([], [IDL.Vec(PaymentRecord)], ['query']),
  'getRegisteredCourses' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
  'getResults' : IDL.Func([], [IDL.Vec(Result)], ['query']),
  'getResultsForStudent' : IDL.Func([IDL.Text], [IDL.Vec(Result)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUserDashboard' : IDL.Func([], [IDL.Text], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'linkParentToStudent' : IDL.Func([IDL.Text], [], []),
  'recordPayment' : IDL.Func([IDL.Nat, IDL.Opt(IDL.Text), IDL.Text], [], []),
  'recordPaymentByAdmin' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'registerCourse' : IDL.Func([IDL.Nat], [], []),
  'registerProfile' : IDL.Func(
      [UserRole, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendAnnouncement' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'submitApplication' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Text, IDL.Vec(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateAdmissionStatus' : IDL.Func([IDL.Nat, AdmissionStatus], [], []),
  'updateHostelApplicationStatus' : IDL.Func(
      [
        IDL.Nat,
        IDL.Variant({
          'pending' : IDL.Null,
          'approved' : IDL.Null,
          'rejected' : IDL.Null,
        }),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AdmissionStatus = IDL.Variant({
    'pending' : IDL.Null,
    'admitted' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const FeeType = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'session' : IDL.Text,
    'amount' : IDL.Nat,
    'programme' : IDL.Text,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const Result = IDL.Record({
    'studentId' : IDL.Text,
    'semester' : IDL.Text,
    'score' : IDL.Nat,
    'grade' : IDL.Text,
    'courseId' : IDL.Nat,
  });
  const PaymentRecord = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Variant({ 'pending' : IDL.Null, 'completed' : IDL.Null }),
    'paymentMethod' : IDL.Text,
    'studentId' : IDL.Text,
    'date' : IDL.Int,
    'feeType' : IDL.Text,
    'reference' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const AdmissionApplication = IDL.Record({
    'id' : IDL.Nat,
    'status' : AdmissionStatus,
    'documents' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'programmeChoice' : IDL.Text,
    'jambNumber' : IDL.Text,
    'oLevelResults' : IDL.Vec(IDL.Text),
  });
  const HostelApplication = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Variant({
      'pending' : IDL.Null,
      'approved' : IDL.Null,
      'rejected' : IDL.Null,
    }),
    'studentId' : IDL.Text,
    'session' : IDL.Text,
    'roomType' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'staff' : IDL.Null,
    'student' : IDL.Null,
    'parent' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'principal' : IDL.Principal,
    'name' : IDL.Text,
    'role' : UserRole,
    'email' : IDL.Text,
    'idNumber' : IDL.Text,
  });
  const Announcement = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'timestamp' : IDL.Int,
    'targetRole' : IDL.Text,
  });
  const Course = IDL.Record({
    'id' : IDL.Nat,
    'semester' : IDL.Text,
    'code' : IDL.Text,
    'name' : IDL.Text,
    'programme' : IDL.Text,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCourse' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
    'addFeeType' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text, IDL.Text], [], []),
    'addResult' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Nat],
        [],
        [],
      ),
    'addStudentProfile' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'applyForHostel' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'assignAccessRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'checkAdmissionStatus' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(AdmissionStatus)],
        ['query'],
      ),
    'checkAdmissionStatusByName' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(AdmissionStatus)],
        ['query'],
      ),
    'checkUnpaidFees' : IDL.Func([], [IDL.Vec(FeeType)], ['query']),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'deregisterCourse' : IDL.Func([IDL.Nat], [], []),
    'getAggregatedStudentData' : IDL.Func(
        [],
        [IDL.Vec(Result), IDL.Vec(PaymentRecord)],
        [],
      ),
    'getAllAdmissionApplications' : IDL.Func(
        [],
        [IDL.Vec(AdmissionApplication)],
        ['query'],
      ),
    'getAllHostelApplications' : IDL.Func(
        [],
        [IDL.Vec(HostelApplication)],
        ['query'],
      ),
    'getAllPayments' : IDL.Func([], [IDL.Vec(PaymentRecord)], ['query']),
    'getAllResults' : IDL.Func([], [IDL.Vec(Result)], ['query']),
    'getAllStudents' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getAllUserProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getAnnouncements' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Announcement)],
        ['query'],
      ),
    'getCallerRole' : IDL.Func([], [IDL.Opt(UserRole)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
    'getFeeTypes' : IDL.Func([], [IDL.Vec(FeeType)], ['query']),
    'getMyHostelApplication' : IDL.Func(
        [],
        [IDL.Opt(HostelApplication)],
        ['query'],
      ),
    'getPaymentHistory' : IDL.Func([], [IDL.Vec(PaymentRecord)], ['query']),
    'getRegisteredCourses' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
    'getResults' : IDL.Func([], [IDL.Vec(Result)], ['query']),
    'getResultsForStudent' : IDL.Func([IDL.Text], [IDL.Vec(Result)], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUserDashboard' : IDL.Func([], [IDL.Text], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'linkParentToStudent' : IDL.Func([IDL.Text], [], []),
    'recordPayment' : IDL.Func([IDL.Nat, IDL.Opt(IDL.Text), IDL.Text], [], []),
    'recordPaymentByAdmin' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'registerCourse' : IDL.Func([IDL.Nat], [], []),
    'registerProfile' : IDL.Func(
        [UserRole, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendAnnouncement' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'submitApplication' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Text, IDL.Vec(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateAdmissionStatus' : IDL.Func([IDL.Nat, AdmissionStatus], [], []),
    'updateHostelApplicationStatus' : IDL.Func(
        [
          IDL.Nat,
          IDL.Variant({
            'pending' : IDL.Null,
            'approved' : IDL.Null,
            'rejected' : IDL.Null,
          }),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };