/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type GeneratePasswordResponse = {
    'ok' : { 'generatedId' : string, 'password' : string }
  } |
  { 'err' : string };
export interface PortalAccessApplication {
  'status' : { 'pending' : null } |
    { 'approved' : null } |
    { 'rejected' : null },
  'applicantName' : string,
  'generatedId' : [] | [string],
  'role' : PortalAccessRole,
  'submittedAt' : bigint,
  'email' : string,
  'generatedPassword' : [] | [string],
  'programmeOrDepartment' : [] | [string],
}
export type PortalAccessRole = { 'admin' : null } |
  { 'staff' : null } |
  { 'student' : null } |
  { 'parent' : null };
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'principal' : Principal,
  'name' : string,
  'role' : UserRole,
  'email' : string,
  'level' : [] | [bigint],
  'idNumber' : string,
  'department' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'staff' : null } |
  { 'student' : null } |
  { 'parent' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'approvePortalAccessApplication' : ActorMethod<
    [string],
    GeneratePasswordResponse
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getMyPortalAccessApplication' : ActorMethod<
    [string],
    [] | [PortalAccessApplication]
  >,
  'getPortalAccessApplications' : ActorMethod<
    [],
    Array<PortalAccessApplication>
  >,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'loginWithIdAndPassword' : ActorMethod<
    [string, string],
    { 'ok' : UserProfile } |
      { 'err' : string }
  >,
  'rejectPortalAccessApplication' : ActorMethod<[string], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'submitPortalAccessApplication' : ActorMethod<
    [string, string, PortalAccessRole, [] | [string]],
    string
  >,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];