/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const GeneratePasswordResponse = IDL.Variant({
  'ok' : IDL.Record({ 'generatedId' : IDL.Text, 'password' : IDL.Text }),
  'err' : IDL.Text,
});
export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const PortalAccessRole = IDL.Variant({
  'admin' : IDL.Null,
  'staff' : IDL.Null,
  'student' : IDL.Null,
  'parent' : IDL.Null,
});
export const PortalAccessApplication = IDL.Record({
  'status' : IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  }),
  'applicantName' : IDL.Text,
  'generatedId' : IDL.Opt(IDL.Text),
  'role' : PortalAccessRole,
  'submittedAt' : IDL.Int,
  'email' : IDL.Text,
  'generatedPassword' : IDL.Opt(IDL.Text),
  'programmeOrDepartment' : IDL.Opt(IDL.Text),
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'staff' : IDL.Null,
  'student' : IDL.Null,
  'parent' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'principal' : IDL.Principal,
  'name' : IDL.Text,
  'role' : UserRole,
  'email' : IDL.Text,
  'level' : IDL.Opt(IDL.Nat),
  'idNumber' : IDL.Text,
  'department' : IDL.Opt(IDL.Text),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'approvePortalAccessApplication' : IDL.Func(
      [IDL.Text],
      [GeneratePasswordResponse],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getMyPortalAccessApplication' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(PortalAccessApplication)],
      ['query'],
    ),
  'getPortalAccessApplications' : IDL.Func(
      [],
      [IDL.Vec(PortalAccessApplication)],
      ['query'],
    ),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'loginWithIdAndPassword' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : UserProfile, 'err' : IDL.Text })],
      ['query'],
    ),
  'rejectPortalAccessApplication' : IDL.Func([IDL.Text], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'submitPortalAccessApplication' : IDL.Func(
      [IDL.Text, IDL.Text, PortalAccessRole, IDL.Opt(IDL.Text)],
      [IDL.Text],
      [],
    ),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const GeneratePasswordResponse = IDL.Variant({
    'ok' : IDL.Record({ 'generatedId' : IDL.Text, 'password' : IDL.Text }),
    'err' : IDL.Text,
  });
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const PortalAccessRole = IDL.Variant({
    'admin' : IDL.Null,
    'staff' : IDL.Null,
    'student' : IDL.Null,
    'parent' : IDL.Null,
  });
  const PortalAccessApplication = IDL.Record({
    'status' : IDL.Variant({
      'pending' : IDL.Null,
      'approved' : IDL.Null,
      'rejected' : IDL.Null,
    }),
    'applicantName' : IDL.Text,
    'generatedId' : IDL.Opt(IDL.Text),
    'role' : PortalAccessRole,
    'submittedAt' : IDL.Int,
    'email' : IDL.Text,
    'generatedPassword' : IDL.Opt(IDL.Text),
    'programmeOrDepartment' : IDL.Opt(IDL.Text),
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'staff' : IDL.Null,
    'student' : IDL.Null,
    'parent' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'principal' : IDL.Principal,
    'name' : IDL.Text,
    'role' : UserRole,
    'email' : IDL.Text,
    'level' : IDL.Opt(IDL.Nat),
    'idNumber' : IDL.Text,
    'department' : IDL.Opt(IDL.Text),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'approvePortalAccessApplication' : IDL.Func(
        [IDL.Text],
        [GeneratePasswordResponse],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getMyPortalAccessApplication' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(PortalAccessApplication)],
        ['query'],
      ),
    'getPortalAccessApplications' : IDL.Func(
        [],
        [IDL.Vec(PortalAccessApplication)],
        ['query'],
      ),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'loginWithIdAndPassword' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : UserProfile, 'err' : IDL.Text })],
        ['query'],
      ),
    'rejectPortalAccessApplication' : IDL.Func([IDL.Text], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'submitPortalAccessApplication' : IDL.Func(
        [IDL.Text, IDL.Text, PortalAccessRole, IDL.Opt(IDL.Text)],
        [IDL.Text],
        [],
      ),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };